//
//  Keys.swift
//  Medical Terminology
//
//  Created by Zaigham Tahir on 2/26/21.
//  Copyright © 2021 Zaigham Tahir. All rights reserved.
//

import Foundation

class MyKeys {
    
    //keys to save data in the userDefaults
	
	let appVersion = "appVersion"
	let appBuild =  "appBuild"
	let showWelcomeScreen = "showWelcomeScreen"
	let appPurchaseStatus = "appPurchaseStatus"
	
	
	// MARK: - notifications for currentCategoryIDs
	
	let currentCategoryIDsChangedKey = "com.theappgalaxy.currentCategoresChanged"
	
	// MARK: - notifications for categories
	
	let categoryNameChangedKey = "com.theappgalaxy.categoryNameUpdatedNotification"
	
	let categoryAddedKey = "com.theappgalaxy.categoryAdded"
	
	// MARK: - notifications for terms
	
	let termAddedKey = "com.theappgalaxy.termAdded"

	/**
	The TermVC will trigger this at any term field change, including favorite change when the user saves the changes
	If the Term categories change, the TermVC will only send out the termCategoryIDsChangedKey even if fields change, as responding to the termCategoyrIDsChangedKey will
	refresh all data anyway
	*/
	let termFieldsChangedKey = "com.theappgalaxy.termFieldsChanged"
	
	/**
	Trigger this if the category changes it's id. the category is changing it's categoryID's AND other fields,
	just trigger the termCategoryIDsChangedN as that function will refresh the data and display
	
	Generated by:
	TermController.updateTerm
	AssignTermsVCH.didSelectRow
	
	Responded by:
	categoryVC/VCH
	categoryListVC/VCH
	flashcard, terms, learningHome, testHome
	
	*/
	let termCategoryIDsChangedKey = "com.theappgalaxy.termCategoryIDsChanged"
	
	let termDeletedKey = "com.theappgalaxy.termDeleted"
	

	/*
	The TermController will send this out when a user presses the favorite button
	Tlashcard
	TermsList
	TermVC (this will be an instant save, not requiring saving).
	
	*/
	let termFavoriteStatusChanged = "com.theappgalaxy.termFavoriteStatusChanged"
	
}

